# Generated by Django 4.2.7 on 2023-12-07 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengurus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('nama', models.CharField(max_length=100)),
                ('fakultas_pengurus', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kehadiran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=100, null=True)),
                ('nama', models.CharField(max_length=100, null=True)),
                ('jurusan', models.CharField(max_length=50, null=True)),
                ('foto_hadir', models.ImageField(upload_to='KehadiranMahasiswa')),
                ('jam_hadir', models.DateTimeField(auto_now_add=True)),
                ('mahasiswa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mahasiswa.mahasiswa')),
            ],
        ),
    ]
