# Generated by Django 4.2.7 on 2023-12-06 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
        ('pengurus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kehadiran',
            name='mahasiswa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mahasiswa.mahasiswa'),
        ),
    ]
