# Generated by Django 4.2.7 on 2023-12-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengurus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kehadiran',
            name='lokasi',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
