# Generated by Django 4.2.7 on 2023-12-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengurus', '0002_kehadiran_lokasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kehadiran',
            name='lokasi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
