# Generated by Django 4.2.7 on 2023-12-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nim', models.CharField(max_length=15)),
                ('alamat', models.TextField()),
                ('foto_mhs', models.ImageField(upload_to='ProfileMahasiswa')),
                ('jenis_kelamin', models.CharField(choices=[('LK', 'Laki-Laki'), ('PR', 'Perempuan')], max_length=2)),
                ('jurusan', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
